# Generated by Django 3.0.7 on 2020-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200807_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transreg',
            name='nogst',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transreg',
            name='nopan',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transreg',
            name='nouidai',
            field=models.CharField(max_length=30),
        ),
    ]
