# Generated by Django 3.0.7 on 2020-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200807_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='company',
            new_name='usercompany',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='contact',
            new_name='usercontact',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='cpassword',
            new_name='usercpwd',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='dob',
            new_name='userdob',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='password',
            new_name='userpwd',
        ),
        migrations.RemoveField(
            model_name='ownerreg',
            name='uidaino',
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='driverno',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='gstuser',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='routeopr',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='truckno',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='uidaiuser',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='transreg',
            name='nogst',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transreg',
            name='nopan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transreg',
            name='nouidai',
            field=models.IntegerField(),
        ),
    ]
