# Generated by Django 3.0.7 on 2020-08-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200808_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='usercompany',
            new_name='ucompany',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='usercontact',
            new_name='ucontact',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='usercpwd',
            new_name='ucpwd',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='userdob',
            new_name='udob',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='useremail',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='username',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='userpwd',
            new_name='upwd',
        ),
    ]
