# Generated by Django 3.0.7 on 2020-08-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200808_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='cpwd',
            new_name='cpassword',
        ),
        migrations.RenameField(
            model_name='ownerreg',
            old_name='pwd',
            new_name='password',
        ),
    ]
