# Generated by Django 3.0.7 on 2020-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200808_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='uidai',
            new_name='uniqueno',
        ),
        migrations.AlterField(
            model_name='ownerreg',
            name='driver',
            field=models.IntegerField(),
        ),
    ]
