# Generated by Django 3.0.7 on 2020-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20200808_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerreg',
            name='unique',
            field=models.CharField(max_length=15),
        ),
    ]
