# Generated by Django 3.0.7 on 2020-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20200808_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerreg',
            name='unique',
        ),
        migrations.AddField(
            model_name='ownerreg',
            name='number',
            field=models.IntegerField(default=''),
        ),
    ]
