# Generated by Django 3.0.7 on 2020-08-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20200808_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='number',
            new_name='num',
        ),
    ]
