# Generated by Django 3.0.7 on 2020-08-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20200808_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerreg',
            old_name='num',
            new_name='addsec',
        ),
    ]
