# Generated by Django 3.0.7 on 2020-08-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20200808_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerreg',
            name='addsec',
        ),
    ]
